#!/bin/sh

ln -sfv `pwd`/.emacs.d $HOME/.
ln -sfv `pwd`/.xmonad $HOME/.
ln -sfv `pwd`/.config/alacritty $HOME/.config/.
ln -sfv `pwd`/.config/bash-insulter $HOME/.config/.
ln -sfv `pwd`/.config/dunst $HOME/.config/.
ln -sfv `pwd`/.config/guitarix $HOME/.config/.
ln -sfv `pwd`/.config/i3 $HOME/.config/.
ln -sfv `pwd`/.config/jack $HOME/.config/.
ln -sfv `pwd`/.config/picom $HOME/.config/.
ln -sfv `pwd`/.config/polybar $HOME/.config/.
ln -sfv `pwd`/.config/ranger $HOME/.config/.
ln -sfv `pwd`/.config/scripts $HOME/.config/.
ln -sfv `pwd`/.config/notes.org $HOME/.config/.
ln -sfv `pwd`/.config/xmobar $HOME/.config/.
ln -sfv `pwd`/.config/.git-prompt.sh $HOME/.config/.
ln -sfv `pwd`/.config/fig $HOME/.config/.
ln -sfv `pwd`/.config/pacwall.png $HOME/.config/.
ln -sfv `pwd`/.config/picom.con $HOME/.config/.
ln -sfv `pwd`/.bash_profile $HOME/.
ln -sfv `pwd`/.bashrc $HOME/.
ln -sfv `pwd`/.fehbg $HOME/.
ln -sfv `pwd`/.gitconfig $HOME/.
ln -sfv `pwd`/.pureline.conf $HOME/.
ln -sfv `pwd`/.vimrc $HOME/.
ln -sfv `pwd`/.xbindkeysrc $HOME/.
ln -sfv `pwd`/.xinitrc $HOME/.
ln -sfv `pwd`/.Xmodmap $HOME/.
