[colors.bright]
black = "0x434758"
blue = "0x9cc4ff"
cyan = "0xa3f7ff"
green = "0xddffa7"
magenta = "0xe1acff"
red = "0xff8b92"
white = "0xffffff"
yellow = "0xffe585"

[colors.normal]
black = "0x282a36"
blue = "0x82aaff"
cyan = "0x89ddff"
green = "0xc3e88d"
magenta = "0xc792ea"
red = "0xf07178"
white = "0xd0d0d0"
yellow = "0xffcb6b"

[colors.primary]
background = "0x282c34"
foreground = "0xbbc5ff"

[colors.selection]
background = "0xbbc5ff"
text = "0x282a36"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "P"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "P"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "P"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "P"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "P"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "N"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "N"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "N"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "N"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "N"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 5000
multiplier = 3

[window]
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
